version: '3.8'

services:
  telegraph-miner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegraph-miner-node
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - SSL_VERIFY=false
